---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
    spec:
      containers:
      - name: dead-simple
        image: {{ .Values.image }}
        ports:
          - name: flask-app
            containerPort: 5000
