apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.exposedHost }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.name }}
          servicePort: 80
