apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http-flask
    port: 80
    targetPort: 5000
  selector:
    app: {{ .Values.name }}
  sessionAffinity: ClientIP
